---
title: "fig6"
author: "Daniel Chawla"
date: "3/18/2022"
output: md_document
---
# Figure 6: Analysis of influenza signatures demonstrates a trade-off be- tween robustness and cross-reactivity

## 6B-C: Robustness and cross-reactivity of published signatures
```{r, include = F, echo = F}
input_dir <- '~/Documents/darpa-manuscript-data/flu_data_v3/'
source('../analysis/plot_palette.R')
```


Calculating AUROCs 
```{r, results = FALSE}
library(dplyr)
library(ggplot2)
library(patchwork)
library(openxlsx)
library(scales)

source('../analysis/helperFunctions.R')

# input contrast group
contrast <- 'healthy'

# healthy and noninf specify controls, original uses the author-supplied contrast
if(!contrast %in% c('healthy', 'noninf', 'original')){
  stop('contrast must be either "healthy", "noninf", or "original"')
}

# current contrast is a dummy variable for modifying the input table before parsing
current_contrast <- 'original'
if(contrast == 'healthy'){
  current_contrast <- 'Healthy'
}
if(contrast == 'noninf'){
  current_contrast <- 'Non-Infectious'
}

# load signatures
signatures <- read.xlsx('~/Dropbox/compendium_manuscript/tables/supp_1.xlsx') %>%
  filter(Type == 'Influenza' | Signature.Label == 'V10')

if(current_contrast != 'original'){
  signatures <- signatures %>%
    mutate(Comparison = current_contrast)
}

# load flu validation data
flu_test <- readRDS(paste0(input_dir, 'flu_test.RDS'))
other_files <- list.files(path = input_dir, pattern = 'other', full.names = T)
other_files <- other_files[!grepl(pattern = 'other_data', x = other_files)]
other_list <- lapply(other_files, readRDS) %>%
  unlist(recursive = F)

# generate AUROCs
out <- list()
for (i in 1:nrow(signatures)){
  current_sig <- sig2Meta(signatures[i,])
  flu_df <- plotDatSignature(signature = current_sig, 
                             data_list = flu_test,
                             pval_calc = F)
  other_df <- plotDatSignature(current_sig, 
                               data_list = other_list, 
                               pval_calc = F)
  
  flu_df <- flu_df %>%
    mutate(Pathogen = 'Influenza')
  other_df <- other_df %>%
    mutate(Pathogen = 'Non-Influenza Virus')
  
  plot_dat <- bind_rows(flu_df, other_df)
  out[[i]] <- plot_dat
}

```


Plotting results
```{r}
plot_dat <- out %>%
  bind_rows()
summary(plot_dat$frac_pos) # all signatures have enough positive and negative gene mappings
summary(plot_dat$frac_neg)

AUC_threshold = 0.7
specificity_threshold = 0.6
gen_labs <- plot_dat %>%
  filter(Pathogen == 'Influenza') %>%
  group_by(Signature, Pathogen) %>%
  summarize('med' = median(Scores)) %>%
  mutate('label' = ifelse(med >= AUC_threshold, 'good generalizability', 'bad generalizability'))
spec_labs <- plot_dat %>%
  filter(Pathogen != 'Influenza') %>%
  group_by(Signature, Pathogen) %>%
  summarize('med' = median(Scores)) %>%
  mutate('label' = ifelse(med >= AUC_threshold, 'non-specific', 'specific'))
label_df <- bind_rows(gen_labs, spec_labs)
plot_dat <- plot_dat %>%
  left_join(label_df)

color_vals <- c('#ea7d9c', '#c4e8f0', 'gray50')
names(color_vals) <- c('Influenza', 'Virus', 'not specific')
p_flu <- ggplot(plot_dat %>% 
                  filter(Pathogen == 'Influenza') %>%
                  mutate(Color = ifelse(!grepl(pattern = 'V10', x = Signature), 'Influenza', 'Virus')), 
                aes(x = Signature, y = Scores, fill = Color)) + 
  geom_boxplot() + 
  #text_geom +
  #geom_hline(yintercept = c(AUC_threshold), color = 'red', linetype = 'dashed') + 
  #geom_hline(yintercept = c(0.5), color = 'black', linetype = 'dashed') + 
  facet_grid(. ~ Pathogen, scales = 'free', space = 'free') + 
  #scale_color_manual(values = color_vals[3:5], name = 'Outlier Points') + 
  #scale_fill_manual(values = color_vals[1:2], name = 'Performance') + 
  scale_alpha(guide = 'none') +
  theme_clean + 
  scale_fill_manual(values = color_vals) +
  theme(axis.text.x = element_text(angle = 0, hjust = 1),
        legend.position = 'none',
        panel.spacing = unit(2, "lines")) + 
  scale_y_continuous(breaks = seq(to = 1, from = 0, by = 0.2), limits = c(0,1)) + 
  labs(y = 'AUROC', x = 'signature') 
p_flu
p_other <- ggplot(plot_dat %>% 
                    filter(Pathogen != 'Influenza') %>% 
                    mutate(Color = ifelse(!grepl(pattern = 'V10', x = Signature), 'not specific', 'Virus')), 
                  aes(x = Signature, y = Scores, fill = Color)) + 
  geom_boxplot() + 
  #text_geom +
  #geom_hline(yintercept = c(specificity_threshold), color = 'blue', linetype = 'dashed') + 
  #geom_hline(yintercept = c(0.5), color = 'black', linetype = 'dashed') + 
  facet_grid(. ~ Pathogen, scales = 'free', space = 'free') + 
  #scale_color_manual(values = color_vals[3:5], name = 'Outlier Points') + 
  #scale_fill_manual(values = color_vals[1:2], name = 'Performance') + 
  scale_alpha(guide = 'none') +
  theme_clean + 
  scale_fill_manual(values = color_vals) +
  theme(axis.text.x = element_text(angle = 0, hjust = 1),
        legend.position = 'none',
        panel.spacing = unit(2, "lines")) + 
  scale_y_continuous(breaks = seq(to = 1, from = 0, by = 0.2), limits = c(0,1)) + 
  labs(y = 'AUROC', x = 'signature') 
p_other

p_flu + p_other
```

## Flu vs. healthy meta-analysis and signature exploration

```{r, echo = F, include = F}
initial_signature <- readRDS('~/Dropbox/flu_sig_102021.RDS')
permuted_signature_scores <- read.csv('~/Dropbox/random_flu_102021.csv')

## merge other_test and other_train based on the number of samples in each
flu_train <- c(readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_disc.RDS'),
               readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_dev.RDS'))
flu_test <- readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_test.RDS')
other_train <- c(readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_disc.RDS'),
                 readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_dev.RDS'))
other_test <- readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_test.RDS')
N1 <- sum(sapply(other_train_list, function(x){nrow(x$pheno)}))
N2 <- sum(sapply(other_test_list, function(x){nrow(x$pheno)}))

N_flu_train <- generateNlist(flu_train)
N_flu_test <- generateNlist(flu_test)
N_other_train <- generateNlist(other_train)
N_other_test <- generateNlist(other_test)

Denom_other_train <- generateDenomlist(other_train)
Denom_other_test <- generateDenomlist(other_test)
```

```{r}
# read permuted signature scores
df <- bind_rows(permuted_signature_scores, 
                scoreSignature(initial_signature, 
                               sum(length(initial_signature$posGeneNames),
                                   length(initial_signature$negGeneNames))) %>% 
                  dplyr::select(-c(posGenes, negGenes)))

# evaluate full signature and append with label
max_ix <- df %>%
  #mutate('diff' = flu_test - other_train) %>%
  mutate('diff' = flu_test - other_test) %>% 
  pull() %>%
  which.max()

pt_color = 'steelblue2'
df <- df %>%
  #mutate('diff' = flu_test - other_train) %>%
  mutate('diff' = flu_test - other_test) %>% 
  #mutate(col_pt = ifelse(diff != max(diff), 'black', 'darkorange2')) %>%
  mutate('col_pt' = ifelse(k != max(k), 'black', pt_color)) %>%
  #mutate(lab_pt = ifelse(diff != max(diff), '', 'Maximum Difference (Specificity)\n 5 genes')) %>%
  mutate('lab_pt' = ifelse(k != max(k), '', paste0('Full Signature\n', df[nrow(df),'k'],' genes')))
  #mutate(col_pt = ifelse(k != max(k), '', 'steelblue3')) %>%
  #mutate(lab_pt = ifelse(k != max(k), '', 'Full Signature\n152 genes')) 

# df2 <- df %>%
#   ungroup() %>% 
#   mutate('other' = (N1 * other_train + N2 * other_test) /(N1 + N2))

p_out <- ggplot(df, aes(x = flu_test, y = other_test))  +
#p_out <- ggplot(df2, aes(x = flu_test, y = other))  +
  theme_bw() + 
  geom_point(color = df$col_pt, alpha = 0.8) + 
  #geom_abline(intercept = 0, slope = 1) + 
  labs(x = 'Avg. AUC Influenza Datasets', y = 'Avg. AUC Non-Influenza Datasets') +
  scale_x_continuous(limits = c(0.5, 1.01), expand = c(0,0)) +
  scale_y_continuous(limits = c(0., 1.01), expand = c(0,0)) +
  #geom_smooth(method = 'lm') + 
  geom_label(data = df %>% 
               filter(df$col_pt != 'black'), 
             aes(x = flu_test, y = other_test, label = lab_pt), color = pt_color, position = position_nudge(x = -0.035, y = 0.07)) + 
  geom_hline(yintercept = 0.6) + 
  geom_vline(xintercept = 0.7) + 
  theme(axis.text = element_text(size = 12))
p_out

```

```{r, echo = F, include = F}
initial_signature <- readRDS('~/Dropbox/flu_vs_virus.RDS')
permuted_signature_scores <- read.csv('~/Dropbox/random_flu_vs_virus_121121.csv')

## merge other_test and other_train based on the number of samples in each
flu_train <- c(readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_disc.RDS'),
               readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_dev.RDS'))
flu_test <- readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/flu_test.RDS')
other_train <- c(readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_disc.RDS'),
                 readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_dev.RDS'))
other_test <- readRDS('~/Documents/darpa-manuscript-data/flu_data_v3/other_test.RDS')
N1 <- sum(sapply(other_train_list, function(x){nrow(x$pheno)}))
N2 <- sum(sapply(other_test_list, function(x){nrow(x$pheno)}))

N_flu_train <- generateNlist(flu_train)
N_flu_test <- generateNlist(flu_test)
N_other_train <- generateNlist(other_train)
N_other_test <- generateNlist(other_test)

Denom_other_train <- generateDenomlist(other_train)
Denom_other_test <- generateDenomlist(other_test)
```

```{r}
# read permuted signature scores
df <- bind_rows(permuted_signature_scores, 
                scoreSignature(initial_signature, 
                               sum(length(initial_signature$posGeneNames),
                                   length(initial_signature$negGeneNames))) %>% 
                  dplyr::select(-c(posGenes, negGenes)))

# evaluate full signature and append with label
max_ix <- df %>%
  #mutate('diff' = flu_test - other_train) %>%
  mutate('diff' = flu_test - other_test) %>% 
  pull() %>%
  which.max()

pt_color = 'steelblue2'
df <- df %>%
  #mutate('diff' = flu_test - other_train) %>%
  mutate('diff' = flu_test - other_test) %>% 
  #mutate(col_pt = ifelse(diff != max(diff), 'black', 'darkorange2')) %>%
  mutate('col_pt' = ifelse(k != max(k), 'black', pt_color)) %>%
  #mutate(lab_pt = ifelse(diff != max(diff), '', 'Maximum Difference (Specificity)\n 5 genes')) %>%
  mutate('lab_pt' = ifelse(k != max(k), '', paste0('Full Signature\n', df[nrow(df),'k'],' genes')))
  #mutate(col_pt = ifelse(k != max(k), '', 'steelblue3')) %>%
  #mutate(lab_pt = ifelse(k != max(k), '', 'Full Signature\n152 genes')) 

# df2 <- df %>%
#   ungroup() %>% 
#   mutate('other' = (N1 * other_train + N2 * other_test) /(N1 + N2))

p_out <- ggplot(df, aes(x = flu_test, y = other_test))  +
#p_out <- ggplot(df2, aes(x = flu_test, y = other))  +
  theme_bw() + 
  geom_point(color = df$col_pt, alpha = 0.8) + 
  #geom_abline(intercept = 0, slope = 1) + 
  labs(x = 'Avg. AUC Influenza Datasets', y = 'Avg. AUC Non-Influenza Datasets') +
  scale_x_continuous(limits = c(0.5, 1.01), expand = c(0,0)) +
  scale_y_continuous(limits = c(0., 1.01), expand = c(0,0)) +
  #geom_smooth(method = 'lm') + 
  geom_label(data = df %>% 
               filter(df$col_pt != 'black'), 
             aes(x = flu_test, y = other_test, label = lab_pt), color = pt_color, position = position_nudge(x = -0.035, y = 0.07)) + 
  geom_hline(yintercept = 0.6) + 
  geom_vline(xintercept = 0.7) + 
  theme(axis.text = element_text(size = 12))
p_out

```

```{r}
color_vals <- c('gray80', 'black')
names(color_vals) <- c('', 'pareto front')
color_vals2 <- c('gray80', 'black')
names(color_vals2) <- c('excluded', 'included')
rank_threshold <- 20

#p1 <- readRDS('~/Dropbox/ggplot_objects/6c_flu_vs_healthy_scatter.RDS')
p2 <- readRDS('~/Dropbox/ggplot_objects/6d_flu_vs_virus_scatter.RDS')

#df1 <- p1$data
df2 <- p2$data

d2 = df2 %>%
  dplyr::select(flu_test, other_test) %>%
  mutate(x = 1-flu_test, y = other_test) %>%
  dplyr::select(x,y)
D2 = d2[order(d2$x,d2$y,decreasing=FALSE),]
front2 = D2[which(!duplicated(cummin(D2$y))),]
dim(front2)

front2_ix <- rownames(front2)

df2 <- df2 %>% 
  mutate(id = 1:nrow(df2)) %>% 
  mutate(color = ifelse(id %in% front2_ix, 'pareto front', ''))

# find points within range of the trend line fit to the pareto front
df2 <- df2 %>%
  filter(flu_test >= 0.65)
pf <- df2 %>% 
  filter(color == 'pareto front')

ggplot(df2, aes(x = flu_test, y = other_test, color = color)) + 
  geom_point() + 
  geom_smooth(data = pf, method = 'loess')

mod <- loess(other_test ~ flu_test, data = pf)

df5 <- df2 %>%
  mutate(pareto = ifelse(color == 'pareto front', 'pareto front', '')) %>% 
  dplyr::select(id, flu_test, other_test, posGenes, negGenes, pareto, k) %>% 
  mutate('pred' = predict(mod, newdata = df2)) %>%
  mutate('resid' = other_test-pred) %>%
  filter(flu_test >= 0.7) %>%
  mutate(bin = cut(flu_test, seq(to = 0.95, from = 0.7, by = 0.05), right = FALSE)) %>%
  #mutate(bin2 = cut(flu_test, seq(to = 0.95, from = 0.7, by = 0.05), right = FALSE)) %>%
  group_by(bin) %>%
  arrange(resid) %>%
  mutate(ranking = 1:n()) %>% 
  ungroup() %>%
  mutate(color = ifelse(ranking <= rank_threshold, 'included', 'excluded')) 


type_i_ifn <- read.table('~/Dropbox/0060337.tsv', header = T)$gene

# df5 <- df2 %>%
#   mutate(pareto = ifelse(color == 'pareto front', 'pareto front', '')) %>% 
#   dplyr::select(id, flu_test, other_test, posGenes, negGenes, pareto, k) %>% 
#   mutate('pred' = predict(mod, newdata = df2)) %>%
#   mutate('resid' = other_test-pred) %>%
#   filter(flu_test >= 0.7) %>%
#   mutate(bin = cut(flu_test, seq(to = 0.95, from = 0.7, by = 0.025), right = FALSE)) %>%
#   group_by(bin) %>%
#   arrange(resid) %>%
#   mutate(ranking = 1:n()) %>% 
#   ungroup() %>%
#   mutate(color = ifelse(pareto == 'pareto front', 'included', 'excluded')) 
fill_vals <- c('white', 'gray50')
names(fill_vals) <- c('pareto front', '')

cor(df5$flu_test, df5$other_test)
p1 <- ggplot(df5[sample(nrow(df5)/20, x = 1:nrow(df5)),], aes(x = flu_test, y = other_test)) + 
  #stat_density_2d(data = df5 %>% filter(color != 'included'),color = 'black') +
  geom_point(data = df5, alpha = 0.01, size = 1) + 
  geom_smooth(method = 'lm', se = F, color = 'black') + 
  geom_text(aes(x = 0.9, y = 0.6, label = 'r = 0.69')) + 
  theme_clean + 
  scale_color_manual(values = color_vals2) + 
  scale_fill_manual(values = fill_vals) + 
  theme(legend.position = 'none') + 
  labs(x = 'mean AUROC in influenza studies', y = 'mean AUC in non-influenza studies')

pdf('~/Dropbox/compendium_manuscript/figures/supplements/supp10.pdf', height = 3, width = 3.5)
p1
dev.off()

cor(df5$flu_test[df5$color == 'included'], df5$k[df5$color == 'included'])
p2 <- ggplot(df5 %>% 
         #filter(pareto == 'pareto front'), #%>%
         filter(color == 'included'),
         aes(x = flu_test, y = k)) + 
  geom_point(pch = 21, size = 3, aes(fill = pareto, color = NULL)) + 
  geom_smooth(method = 'lm', se=F, aes(color = color)) + 
  geom_text(data = data.frame(label = 'r = 0.49', flu_test = 0.75, k = 50), aes(label = label, color = NULL)) + 
  ylim(0,62) +  
  theme_clean + 
  scale_color_manual(values = color_vals2) + 
  scale_fill_manual(values = fill_vals) + 
  labs(y = 'signature size', x = 'mean AUC in influenza studies') + 
  theme(legend.position = 'none')

cor(df5$other_test[df5$color == 'included'], df5$k[df5$color == 'included'])^2
p2_other <- ggplot(df5 %>% 
               #filter(pareto == 'pareto front'), #%>%
               filter(color == 'included'),
             aes(x = other_test, y = k)) + 
  geom_point(pch = 21, size = 3, aes(fill = pareto, color = NULL)) + 
  geom_smooth(method = 'lm', se=F, aes(color = color)) + 
  geom_text(data = data.frame(label = 'r = 0.52', other_test = 0.5, k = 50), aes(label = label, color = NULL)) + 
  ylim(0,62) +  
  theme_clean + 
  scale_color_manual(values = color_vals2) + 
  scale_fill_manual(values = fill_vals) + 
  labs(y = 'signature size', x = 'mean AUC in non-influenza studies') + 
  theme(legend.position = 'none')

pdf('~/Dropbox/compendium_manuscript/figures/supplements/supp11.pdf', width = 3.5, height = 3)
p2_other
dev.off()


getGeneVect <- function(gene_df_row){
  if(nrow(gene_df_row) != 1){
    stop('only pass in one row')
  }
  gene_df_row %>%
    mutate(genes = paste0(posGenes, ';', negGenes)) %>%
    mutate(genes = posGenes) %>%
    pull(genes) %>%
    strsplit(split = ';') %>%
    unlist() %>%
    mapIds(x = org.Hs.eg.db, keytype = 'ENTREZID', column = 'SYMBOL') %>%
    unique() %>%
    return()
}

input_df <- df5 %>% 
  filter(color == 'included')
input_genes <- list()
for (i in 1:nrow(input_df)){
  input_genes[[i]] <- getGeneVect(input_df[i,])
}

num_ifn <- sapply(input_genes, function(x){return(sum(x %in% type_i_ifn))})
num_genes <- sapply(input_genes, length)
plot_dat <- input_df %>%
  mutate('num_overlap' = num_ifn, 'num_genes' = num_genes) %>%
  mutate('fraction_overlap' = num_overlap/num_genes) %>%
  mutate('num_non0' = num_overlap > 0)

plot_dat2 <- plot_dat %>%
  group_by(bin) %>%
  summarize('num_non0' = mean(num_non0))
p3 <- ggplot(plot_dat2, aes(x = bin, y = num_non0, group = 1)) +
  #geom_bar(stat = 'identity', color = 'black', fill = 'black') +
  geom_line() +
  geom_point() +
  theme_bw() +
  #ylim(c(0,.75)) +
  theme_clean +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  labs(y = 'fraction of signatures\nwith type I ifn genes', x = 'mean AUC in influenza studies')
p3

# what does specificity look like across the range of bins?
# check aging first
source(paste0(Sys.getenv('DARPA'), 'helperFunctions.R'))
sig_input_df <- input_df %>% 
  dplyr::rename(Positive.Genes = posGenes, Negative.Genes = negGenes) %>%
  mutate('Author' = 'perm', 'Positive.Class' = 'influenza', 'Negative.Class' = 'healthy', 'Discovery.Accessions' = '', 'Validation.Accessions' = '')
sig_list <- list()
for (i in 1:nrow(sig_input_df)){
  current_sig <- list()
  current_sig$posGeneNames <- as.character(parseSets(sig_input_df$Positive.Genes[i]))
  current_sig$negGeneNames <- as.character(parseSets(sig_input_df$Negative.Genes[i]))
  current_sig$filterDescription <- i
  sig_list[[i]] <- current_sig
}

aging_list <- readRDS(file = '~/Documents/darpa-manuscript-data/data_list_final/aging_list.RDS')

sig_input_df <- sig_input_df %>%
  mutate(sig_id = 1:nrow(sig_input_df))
output_list <- list()
for(i in 1:length(sig_list)){
  output_list[[i]] <- plotDatSignature(signature = sig_list[[i]], data_list = aging_list) %>%
    mutate(sig_id = i)
}

aging_plot_dat <- bind_rows(output_list) %>%
  left_join(sig_input_df %>% dplyr::select(k, sig_id, bin))

aging_plot_dat2 <- aging_plot_dat %>%
  group_by(sig_id, bin) %>%
  summarize('med' = median(Scores))

ggplot(aging_plot_dat2, aes(x = bin, y = med)) + 
  geom_boxplot() + 
  theme_clean + 
  #ylim(c(0,1)) + 
  geom_hline(yintercept = 0.6, color = 'gray50', linetype = 'dashed') + 
  labs('title' = 'Influenza Signatures, Aging Data')
```

